# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: df182fea6c31dcd14a82104b1ea612b1cbd37ac53b847ca83eae546969e2bb31ca3af1bd32a5ad643b4060eeeccbc07a2154b107586da526973839b354cfcb27

test:
  secret_key_base: aa02bdbd8dea54a05f01da596511a98a553d619355aa6e6a9a329b207ca28aa8deff60dd06c2be54bcf3ba5dae3e186a6ce771a0d57407938d8731e57e757125

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
